version: '3.8'

services:
  # Service untuk aplikasi Go
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=dev
      - PORT=8081
      - DB_HOST=db
      - DB_USER=postgres.oczurxscwnpcgcyzgdtt
      - DB_PASS=oCbwpF1Tqitp7RCW
      - DB_NAME=postgres
      - CLOUDINARY_CLOUD_NAME=dt0mgikcn
      - CLOUDINARY_API_KEY=355633635416765
      - CLOUDINARY_API_SECRET=-EBiYMn5phQRIHPtHvvzpjEqc8s
      - DATABASE_URL=postgresql://postgres.oczurxscwnpcgcyzgdtt:oCbwpF1Tqitp7RCW@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh & tail -f /dev/null"]

  # Service untuk PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres.oczurxscwnpcgcyzgdtt
      POSTGRES_PASSWORD: Wanjaywkwkwk12!
    ports:
      - "6543:6543"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
